### ISSUE TITLE
flask inner server console display in a mess

### ISSUE THREAD

**Issue by linkmyth** [gothinkster/flask-realworld-example-app#4]
`127.0.0.1 - - [12/Jul/2017 23:30:15] code 400, message Bad request version ('\xcc\xa9\xcc▒▒\xcc\x14\xcc\x13\xc0+\xc0/\xc0')
127.0.0.1 - - [12/Jul/2017 23:30:15] "\xbe\xba\xe5\x9b▒▒K\xe3
                                                             \\xf5-U\xe3ou\xbe&M\x83O\xd3cTN\xf0V\xf4\xef\xa2\x95\xcc\xa9\xcc▒▒\xcc\xcc\xc0+\xc0/\xc0" 400 -
127.0.0.1 - - [12/Jul/2017 23:30:15] code 400, message Bad request version ('\xcc\xa9\xcc▒▒\xcc\x14\xcc\x13\xc0+\xc0/\xc0')
`

When the client connect to the flask server, it just print something above. My computer has always work well with flask inner server console display. And i cannot figure out what's wrong with it.

**Comment by realazizk** [comment]
@linkmyth this needs more details, which fronted are you using, and are you trying to use https  protocol?

**Comment by realazizk** [comment]
I am pretty sure this is happening because you are trying to access it using https, I'm closing this.
