### ISSUE TITLE
ImportError: No module named flask_jwt

### ISSUE THREAD

**Issue by rustanacexd** [gothinkster/flask-realworld-example-app#7]
http://take.ms/qEyVW

Steps to replicate:

exactly followed the steps until ```flask db init```

using python 3.6

**Comment by realazizk** [comment]
Hey, not sure why this happens but can you rerun `pip install -r requirements/dev.txt` ?
If not can you paste the output of `pip freeze`?

**Comment by rustanacexd** [comment]
I already did
http://take.ms/XO1NB

```
alembic==0.9.4
apispec==0.22.3
bcrypt==3.1.3
beautifulsoup4==4.6.0
cffi==1.10.0
click==6.7
factory-boy==2.8.1
Faker==0.7.7
Flask==0.12.1
flask-apispec==0.3.2
Flask-Bcrypt==0.7.1
Flask-Caching==1.2.0
Flask-Cors==3.0.2
Flask-JWT==0.3.2
Flask-Migrate==2.0.3
Flask-Script==2.0.5
Flask-SQLAlchemy==2.2
gunicorn==19.7.1
itsdangerous==0.24
Jinja2==2.9.6
Mako==1.0.7
MarkupSafe==1.0
marshmallow==2.13.5
psycopg2==2.6.2
py==1.4.34
pycparser==2.18
PyJWT==1.5.0
pytest==3.0.6
python-dateutil==2.6.1
python-editor==1.0.3
PyYAML==3.12
six==1.10.0
SQLAlchemy==1.1.9
unicode-slugify==0.1.3
Unidecode==0.4.21
waitress==1.0.2
webargs==1.8.1
WebOb==1.7.3
WebTest==2.0.25
Werkzeug==0.12.1
```

**Comment by realazizk** [comment]
Not sure why but you installed your requirements with python3.6 and running it with python2.7 can you paste the output of `which flask`?

**Comment by rustanacexd** [comment]
ohh thanks. fixed. did run `pip freeze | xargs pip uninstall -y` and then re did `pip install -r requirements/dev.txt`

**Comment by realazizk** [comment]
cool.
