### ISSUE TITLE
replace flask jwt module

### ISSUE THREAD

**Issue by rustanacexd** [gothinkster/flask-realworld-example-app#9]
I checked https://github.com/mattupstate/flask-jwt and it seems dead to me, I also read the issues.  probably use this one? https://github.com/vimalloc/flask-jwt-extended  thoughts?

**Comment by realazizk** [comment]
Yes, it seems that mattupstate/flask-jwt is dead, I'm not able to work on a patch right now, can you find the time to make it, I will be happy to accept a pull request on this one.

**Comment by rustanacexd** [comment]
will do

**Comment by alessandrojcm** [comment]
Done in #15, please check it out.
